name: platform_information_web
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'
 
flutter:
  plugin:
    platforms:
      web:
        pluginClass: PlatformInformationWeb
        fileName: platform_information_web.dart 

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  platform_information_platform_interface:
    path: ../platform_information_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

