name: platform_information
description: "A plugin for getting platform information"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: platform_information_android
      web:
        default_package: platform_information_web
       
dependencies:
  flutter:
    sdk: flutter
  platform_information_android:
    path: ../platform_information_android  
  platform_information_platform_interface:
    path: ../platform_information_platform_interface
  platform_information_web:
    path: ../platform_information_web

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
